### ISSUE TITLE
sleighhome is not set properly

### ISSUE THREAD

**Issue by Liorst4** [radareorg/radare2-snap#3]
Just tried a fresh install of r2 from the snap store.
When I tried to use `pdg`, I got an error message

> ERROR: No languages available, make sure r2ghidra.sleighhome is set properly
   WARN: Ghidra Decompiler Error: Architecture string does not look like sleigh id: gcc

    > e r2ghidra.sleighhome
    /snap/radare2/<SNAP_NUMBER>/lib/radare2/5.8.8

Inside that directory there is another directory named `r2ghidra_sleigh`
Changing that setting to point to that directory fixes the issue

    > e r2ghidra.sleighhome=/snap/radare2/<SNAP_NUMBER>/lib/radare2/5.8.8/r2ghidra_sleigh

I believe that setting is configured here https://github.com/radareorg/radare2-snap/blob/ddb3a7c41f3046649a8ed4ae3b6bcd501f20b135/docker/Dockerfile#L150

**Comment by prodrigestivill** [comment]
Fixed in the git and started build to upload both snap apps and docker images.

Thank you for reporting! :)

**Comment by prodrigestivill** [comment]
Published the new snap revision 2481 for amd64.

Thanks again.
